"""
Django settings for neom project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path

# =============================
# Base Directory
# =============================
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================
# Security
# =============================
SECRET_KEY = 'django-insecure-5titn-s-47290pox27zwse6q96z4$6^elea+&h@vv94^$j3q3-'

DEBUG = True

ALLOWED_HOSTS = []


# =============================
# Applications
# =============================
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'accounts',
    'catalog',
    'orders',
]


# =============================
# Middleware
# =============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # مهم للتعريب
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =============================
# URLs
# =============================
ROOT_URLCONF = 'neom.urls'


# =============================
# Templates Configuration
# =============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # 👇 هنا تعريف مجلد templates العام
        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =============================
# WSGI
# =============================
WSGI_APPLICATION = 'neom.wsgi.application'


# =============================
# Database
# =============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =============================
# Password Validation
# =============================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================
# Internationalization
# =============================
LANGUAGE_CODE = 'ar'

LANGUAGES = [
    ('ar', 'Arabic'),
    ('en', 'English'),
]

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# =============================
# Static Files
# =============================
STATIC_URL = 'static/'


# =============================
# Default PK
# =============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================
# Custom User Model
# =============================
AUTH_USER_MODEL = 'accounts.User'
